# toes-apiserver 全配置

# REST-ful Server
server:
  mode: debug # apiserver mode: release, debug, test，默认 release
  addr: :8080

# MySQL
mysql:
  host: rm-uf65u18gj63n1eqplko.mysql.rds.aliyuncs.com # MySQL 机器 ip 和端口，默认 127.0.0.1:3306
  username: root # MySQL 用户名(建议授权最小权限集)
  password: 5SsmywjqCYjo8gDcKsfRCOKY07jTS8ov1dQl8a9Lz6M= # MySQL 用户密码
  database: xingzhi # 系统所用的数据库名
  maxIdleConnections: 100 # MySQL 最大空闲连接数，默认 100
  maxOpenConnections: 100 # MySQL 最大打开的连接数，默认 100
  maxConnectionLifeTime: 10s # 空闲连接最大存活时间，默认 10s
  logLevel: 4 # GORM log level, 1: silent, 2:error, 3:warn, 4:info
  passwordMode: raw # 密码加密模式，raw:明文

# Redis
redis:
  host: 127.0.0.1:6379 # redis 地址，默认 127.0.0.1:6379
  username: # 用户名
  password: 3k7BqcQV3O+JTbnaybg+TA== # redis 密码


log:
  level: debug # 日志级别，优先级从低到高依次为：debug, info, warn, error, dpanic, panic, fatal。
  days: 7 # 日志保留天数
  format: raw # 支持的日志输出格式，目前支持 raw 和 json 两种。raw 其实就是text格式 行输出。
  console: true # 是否同步输出到命令行
  path: ./logs/log.log


# 加密之后
seckey:
  jwtKey: eDhkc2FmYXNkZjk4YXNkZmphc2RmaTkw #
  jwtttl: 1024 # token 过期时间(分钟)
  pproftoken : off # 配置访问 pprof 是否启用 token 检查


# 防重放
checkHeader:
  all: false # 放重放总开关
  nonce: true # 随机数 开关
  nonceCacheSeconds: 30 # 单位 s
  time: true # 时间戳 开关
  seconds: 120 # 单位 s
  sign: true # 签名检查开关
  key: "" # 防重放 sign 使用


# 请求头相关配置
header:
  realip: x-realip-from
  requestid: x-request-id